A compiler is a program that writes programs.

Before we write our first compiler, let's build a simple program using
standard Linux tools.

* A Simple Program

The simplest thing a program can do is return with an exit code. In C,
we'd write this:

#+BEGIN_SRC c
int main() {
    return 42;
}
#+END_SRC

Which is equivalent to:

#+BEGIN_SRC c
#include <stdlib.h>

int main() {
    exit(42);
}
#+END_SRC

* System Calls

The operating system is responsible for starting and stopping
programs. ~exit()~ stops the program by asking the operating system to
do so.

This is a system call, and every system call is [[http://www.linfo.org/system_call_number.html][assigned a number]]. We
ask Linux to run a system call by putting the system call number ~eax~
register, and triggering an interrupt.

#+BEGIN_SRC assembler
; exit.s
movl $1, %eax  ; store the system call number in eax
movl $42, %ebx ; store the argument (42) to the system call
int $0x80      ; trigger the interrupt
#+END_SRC

These are three instructions executed by the CPU.

* Raw Instructions

~exit.s~ is a text file. Our computer works in bytes, so we must convert
this text file to bytes for these instructions.

#+BEGIN_SRC sh
$ as exit.s -o exit.o
#+END_SRC

This is exactly equivalent to our text file.

#+BEGIN_SRC sh
$ objdump -d exit.o

exit.o:     file format elf64-x86-64


Disassembly of section .text:

0000000000000000 <.text>:
   0:	b8 01 00 00 00       	mov    $0x1,%eax
   5:	bb 2a 00 00 00       	mov    $0x2a,%ebx
   a:	cd 80                	int    $0x80
#+END_SRC

Note that our first two instructions are 5 bytes, whereas our third
instruction is only 2 bytes.

* Creating A Program

However, instructions aren't enough to actually run our program. Linux
executes ELF files. ELF files have headers and metadata in them so the
kernel knows the file is a program.

The linker, ~ld~, creates an executable file which we can run.

#+BEGIN_SRC sh
$ ld exit.o -o exit
$ ./exit 
# Check we got the exit code expected.
$ echo $?
42
#+END_SRC
